============================= test session starts =============================
platform win32 -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0
rootdir: C:\Users\Tina\cs-reminibot\basestation\tests
collected 12 items

chatbot_db_test.py ........F...                                          [100%]

================================== FAILURES ===================================
____________________________ test_commit_db_guest _____________________________

client = <FlaskClient <Flask 'basestation'>>

    def test_commit_db_guest(client):
        """try to commit to database if not logged in"""
    
>       response = client.post(
            '/chatbot-context',
            data = json.dumps(dict(command = 'commit-to-db')),
            content_type='application/json'
        )

chatbot_db_test.py:183: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\..\AppData\Roaming\Python\Python38\site-packages\werkzeug\test.py:1016: in post
    return self.open(*args, **kw)
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\testing.py:222: in open
    return Client.open(
..\..\..\AppData\Roaming\Python\Python38\site-packages\werkzeug\test.py:970: in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
..\..\..\AppData\Roaming\Python\Python38\site-packages\werkzeug\test.py:861: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
..\..\..\AppData\Roaming\Python\Python38\site-packages\werkzeug\test.py:1096: in run_wsgi_app
    app_rv = app(environ, start_response)
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\app.py:2463: in __call__
    return self.wsgi_app(environ, start_response)
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\app.py:2449: in wsgi_app
    response = self.handle_exception(e)
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\app.py:1866: in handle_exception
    reraise(exc_type, exc_value, tb)
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py:39: in reraise
    raise value
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\app.py:2446: in wsgi_app
    response = self.full_dispatch_request()
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\app.py:1951: in full_dispatch_request
    rv = self.handle_user_exception(e)
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\app.py:1820: in handle_user_exception
    reraise(exc_type, exc_value, tb)
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py:39: in reraise
    raise value
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\app.py:1949: in full_dispatch_request
    rv = self.dispatch_request()
..\..\..\AppData\Roaming\Python\Python38\site-packages\flask\app.py:1935: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
..\routes\chatbot_routes.py:45: in chatbot_context
    returned = base_station.update_chatbot_context_db()
..\base_station.py:769: in update_chatbot_context_db
    user_id = self.get_user_id_by_email(user_email)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <basestation.base_station.BaseStation object at 0x000001C994C3B880>
email = ''

    def get_user_id_by_email(self, email: str) -> int:
        user = User.query.filter(User.email == email).first()
>       return user.id
E       AttributeError: 'NoneType' object has no attribute 'id'

..\base_station.py:703: AttributeError
---------------------------- Captured stdout call -----------------------------
user email 
commit context stack to db ['The sky is blue.']
2022-09-10 14:05:27,724 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2022-09-10 14:05:27,724 INFO sqlalchemy.engine.base.Engine SELECT user.id AS user_id, user.email AS user_email, user.password_digest AS user_password_digest, user.custom_function AS user_custom_function 
FROM user 
WHERE user.email = ?
 LIMIT ? OFFSET ?
2022-09-10 14:05:27,725 INFO sqlalchemy.engine.base.Engine ('', 1, 0)
------------------------------ Captured log call ------------------------------
INFO     sqlalchemy.engine.base.Engine:log.py:110 BEGIN (implicit)
INFO     sqlalchemy.engine.base.Engine:log.py:110 SELECT user.id AS user_id, user.email AS user_email, user.password_digest AS user_password_digest, user.custom_function AS user_custom_function 
FROM user 
WHERE user.email = ?
 LIMIT ? OFFSET ?
INFO     sqlalchemy.engine.base.Engine:log.py:110 ('', 1, 0)
============================== warnings summary ===============================
chatbot_db_test.py::test_ping
  C:\Users\Tina\AppData\Roaming\Python\Python38\site-packages\flask_sqlalchemy\__init__.py:813: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
FAILED chatbot_db_test.py::test_commit_db_guest - AttributeError: 'NoneType' ...
=================== 1 failed, 11 passed, 1 warning in 4.04s ===================
